bag/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('add-to-bag/<int:product_id>/', views.add_to_bag, name='add_to_bag'),
    path('remove-from-bag/<int:product_id>/', views.remove_from_bag, name='remove_from_bag'),
    path('view-bag/', views.view_bag, name='view_bag'),
]

ecommerce_project/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('home.urls')),
    path('profile/', include('profiles.urls')),
    path('orders/', include('orders.urls')), 
    path('newsletter/', include('newsletter.urls')),
    path('wishlist/', include('wishlist.urls')),
    path('stock/', include('stock.urls')),
    path('bag/', include('bag.urls')),
    path('checkout/', include('checkout.urls')),
]

orders/urls.py
from django.urls import path
from .views import UserOrdersView, UserOrderDetailsView, CancelOrderView

app_name = 'orders'

urlpatterns = [
    path('user/orders/', UserOrdersView.as_view(), name='user_order_list'),
    path('user/orders/<slug:order_number>/', UserOrderDetailsView.as_view(), name='user_order_detail'),
    path('user/orders/<slug:order_number>/cancel/', CancelOrderView.as_view(), name='cancel_order'),
]

profiles/urls.py
from django.urls import path
from .views import (
    ProfileView, EditUserProfileView,
    AddressesView, EditAddressView, DeleteAddressView,
    ChangePrimaryAddressView, DeleteProfileView
)

app_name = 'profiles'

urlpatterns = [
    path('profile/', ProfileView.as_view(), name='profile'),
    path('edit_profile/', EditUserProfileView.as_view(), name='edit_profile'),
    path('addresses/', AddressesView.as_view(), name='addresses'),
    path('edit_address/<int:address_id>/', EditAddressView.as_view(), name='edit_address'),
    path('delete_address/<int:address_id>/', DeleteAddressView.as_view(), name='delete_address'),
    path('change_primary_address/<int:address_id>/', ChangePrimaryAddressView.as_view(), name='change_primary_address'),
    path('delete_profile/', DeleteProfileView.as_view(), name='delete_profile'),
]

wishlist/urls.py
# urls.py in your wishlist app
from django.urls import path

from . import views

app_name = 'wishlist'

urlpatterns = [
    path('view/', views.view_wishlist, name='view_wishlist'),
    path('add/<int:product_id>/', views.add_to_wishlist, name='add_to_wishlist'),
    path('remove/<int:product_id>/', views.remove_from_wishlist, name='remove_from_wishlist'),
    path('clear/', views.clear_wishlist, name='clear_wishlist'),
]

profiles/models.py
from django.db import models
from django.contrib.auth.models import User
from django_countries.fields import CountryField
from cloudinary_storage.storage import RawMediaCloudinaryStorage

class Profile(models.Model):
    """Model for the profiles."""
    user = models.OneToOneField(
        User,
        on_delete=models.CASCADE,
        related_name='profile',
        verbose_name='User',
        help_text='format: required, unique=True'
    )
    
    first_name = models.CharField(
        max_length=50,
        blank=True,
        null=True,
        verbose_name='First name',
        help_text='format: not required, max_length=50'
    )
    last_name = models.CharField(
        max_length=50,
        blank=True,
        null=True,
        verbose_name='Last name',
        help_text='format: not required, max_length=50'
    )
    profile_picture = models.ImageField(
        upload_to='profile_pictures/',
        null=True,
        blank=True,
        storage=RawMediaCloudinaryStorage()
    )
    
    created_at = models.DateTimeField(
        auto_now_add=True,
        verbose_name='Created at',
    )
    updated_at = models.DateTimeField(
        auto_now=True,
        verbose_name='Updated at'
    )
    
    def __str__(self):
        if self.first_name and self.last_name:
            return f'{self.first_name} {self.last_name}'
        if self.first_name:
            return self.first_name
        return self.user.username


class Address(models.Model):
    """Model for the addresses."""
    profile = models.ForeignKey(
        Profile,
        on_delete=models.CASCADE,
        related_name='addresses',  # Add a related_name to access addresses from a profile
        verbose_name='Profile',
        help_text=(
            'format: required'
        )
    )
    address_line = models.CharField(
        max_length=100,
        verbose_name='Address line',
        help_text=(
            'format: required, max_length=100'
        )
    )
    city = models.CharField(
        max_length=50,
        verbose_name='City',
        help_text=(
            'format: required, max_length=50'
        )
    )
    country = CountryField(
        blank_label='Country *',
        null=False,
        blank=False,
        verbose_name='Country',
        help_text='format: required'
    )
    county_region = models.CharField(
        max_length=50,
        verbose_name='County/Region',
        help_text=(
            'format: required, max_length=50'
        )
    )
    zip_code = models.CharField(
        max_length=20,
        verbose_name='Zip code',
        help_text=(
            'format: required, max_length=20'
        )
    )
    is_primary = models.BooleanField(
        default=False,
        verbose_name='Primary',
        help_text=(
            'format: not required'
        )
    )
    phone_number = models.CharField(
        max_length=20,
        verbose_name='Phone number',
        help_text=(
            'format: required, max_length=20'
        )
    )
    created_at = models.DateTimeField(
        auto_now_add=True,
        verbose_name='Created at',
    )
    updated_at = models.DateTimeField(
        auto_now=True,
        verbose_name='Updated at',
    )

    def __str__(self):
        """Return the address line."""
        return f'{self.profile.user.username} - {self.zip_code} - {self.is_primary}'

    def save(self, *args, **kwargs):
        """Check if there is a primary address."""
        super().save(*args, **kwargs)
        if self.is_primary:
            for address in self.profile.addresses.all().exclude(id=self.id):
                address.is_primary = False
                address.save()

profiles/forms.py
from django import forms
from django_countries.fields import CountryField
from django_countries.widgets import CountrySelectWidget
from .models import Profile, Address
from django_countries import countries

class ProfileForm(forms.ModelForm):
    """Form for the Profile model."""
    class Meta:
        model = Profile
        fields = ['first_name', 'last_name', 'profile_picture']
        help_texts = {
            'first_name': '',  # Remove help text for first_name
            'last_name': '',   # Remove help text for last_name
        }
        widgets = {
            'first_name': forms.TextInput(
                attrs={
                    'class': 'form-control',
                    'placeholder': 'First name',
                }
            ),
            'last_name': forms.TextInput(
                attrs={
                    'class': 'form-control',
                    'placeholder': 'Last name',
                }
            ),
            'profile_picture': forms.HiddenInput(),  # Hide the profile picture input
        }


class AddressForm(forms.ModelForm):
    country = CountryField().formfield(
        widget=CountrySelectWidget(attrs={'class': 'form-control'}),
        choices=countries  # Provide the list of countries
    )

    class Meta:
        model = Address
        fields = [
            'country',
            'county_region',
            'city',
            'address_line',
            'zip_code',
            'phone_number',
            'is_primary'
        ]
        help_texts = {
            field: '' for field in fields  # Remove help text for all fields
        }
        widgets = {
            'county_region': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'County/Region'}),
            'city': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'City'}),
            'address_line': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Address Line'}),
            'zip_code': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Zip Code'}),
            'phone_number': forms.TextInput(
                attrs={'class': 'form-control', 'maxlength': '20', 'placeholder': 'Phone Number'}
            ),
            'is_primary': forms.CheckboxInput(attrs={'class': 'form-check-input'})
        }

profiles/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.views import View
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import Profile, Address
from .forms import ProfileForm, AddressForm
from django.contrib import messages

class ProfileView(LoginRequiredMixin, View):
    """View for displaying user profile."""

    def get(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            profile = request.user.profile
            addresses = profile.addresses.all()
            return render(request, 'profiles/profile.html', {'profile': profile, 'addresses': addresses})
        else:
            return render(request, 'account/login.html')

class EditUserProfileView(LoginRequiredMixin, View):
    """View for editing user profile."""

    def get(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            profile = get_object_or_404(Profile, user=request.user)
            profile_form = ProfileForm(instance=profile)
            address_form = AddressForm(instance=profile.addresses.first())
            return render(request, 'profiles/edit_profile.html', {'profile_form': profile_form, 'address_form': address_form})
        else:
            return render(request, 'account/login.html')

    def post(self, request, *args, **kwargs):
        profile = request.user.profile
        profile_form = ProfileForm(request.POST, request.FILES, instance=profile)
        address_instance = profile.addresses.first() if profile.addresses.exists() else None
        address_form = AddressForm(request.POST, instance=address_instance)
        if profile_form.is_valid() and address_form.is_valid():
            profile_instance = profile_form.save()
            address_instance = address_form.save(commit=False)
            address_instance.profile = profile_instance
            address_instance.save()
            messages.success(request, 'Changes have been saved.')  # Display success message
            return redirect('profiles:edit_profile')  # Stay on the edit_profile page
        return render(request, 'profiles/edit_profile.html', {'profile_form': profile_form, 'address_form': address_form})

class AddressesView(LoginRequiredMixin, View):
    """View for displaying user addresses."""

    def get(self, request, *args, **kwargs):
        profile = request.user.profile
        addresses = profile.addresses.all()
        return render(request, 'profiles/addresses.html', {'profile': profile, 'addresses': addresses})


class EditAddressView(LoginRequiredMixin, View):
    """View for editing an existing address."""

    def get(self, request, address_id, *args, **kwargs):
        address = get_object_or_404(Address, pk=address_id, profile=request.user.profile)
        form = AddressForm(instance=address)
        return render(request, 'profiles/edit_address.html', {'form': form})

    def post(self, request, address_id, *args, **kwargs):
        address = get_object_or_404(Address, pk=address_id, profile=request.user.profile)
        form = AddressForm(request.POST, instance=address)
        if form.is_valid():
            form.save()
            return redirect('addresses')
        return render(request, 'profiles/edit_address.html', {'form': form})

class DeleteAddressView(LoginRequiredMixin, View):
    """View for deleting an existing address."""

    def post(self, request, address_id, *args, **kwargs):
        address = get_object_or_404(Address, pk=address_id, profile=request.user.profile)
        address.delete()
        return redirect('addresses')

    def get(self, request, address_id, *args, **kwargs):
        address = get_object_or_404(Address, pk=address_id, profile=request.user.profile)
        return render(request, 'profiles/delete_address.html', {'address': address})

class ChangePrimaryAddressView(LoginRequiredMixin, View):
    """View for changing the primary address."""

    def post(self, request, address_id, *args, **kwargs):
        profile = request.user.profile
        address = get_object_or_404(Address, pk=address_id, profile=profile)
        if address != profile.primary_address:  # Only save if primary address changes
            profile.primary_address = address
            profile.save()
        return redirect('addresses')

class DeleteProfileView(LoginRequiredMixin, View):
    """View for deleting user profile."""

    def get(self, request, *args, **kwargs):
        return render(request, 'profiles/delete_profile.html')

    def post(self, request, *args, **kwargs):
        user = request.user
        user.delete()
        return HttpResponseRedirect(reverse('home'))  # Redirect to home page

profiles/templates/profiles/addresses.html
{% extends 'base.html' %}

{% block content %}
<style>
    .charcoal-container {
        background-color: rgba(55, 55, 55, 0.8);
        padding: 20px;
        border-radius: 10px;
        margin: 50px auto 20px;
        max-width: 800px;
    }

    .address-card {
        background-color: #333333;
        color: #ffffff;
        border-radius: 8px;
        margin-bottom: 20px;
        padding: 20px;
    }

    .primary-badge {
        background-color: #c9fa04;
        color: #000000;
        padding: 5px 10px;
        border-radius: 5px;
        font-size: 14px;
    }

    .neon-green-btn {
        background-color: #c9fa04;
        color: #000000;
        border: none;
        border-radius: 5px;
        padding: 10px 20px;
        font-size: 16px;
        cursor: pointer;
        margin-top: 20px;
        transition: background-color 0.3s ease, color 0.3s ease;
        text-decoration: none;
        display: inline-block;
    }

    .neon-green-btn:hover {
        background-color: #01331a;
        color: #ffffff;
    }
</style>

<div class="charcoal-container">
    <h2 class="text-center text-white mb-4">Addresses</h2>
    <div class="row justify-content-center">
        <div class="col-md-8">
            {% for address in addresses %}
            <div class="address-card">
                <p>{{ address.address_line }}</p>
                <p>{{ address.city }}, {{ address.county_region }}, {{ address.country }} {{ address.zip_code }}</p>
                {% if address.is_primary %}
                <span class="primary-badge">Primary</span>
                {% endif %}
            </div>
            {% endfor %}
        </div>
    </div>
    <div class="col-md-12 text-center mt-5">
        <a href="{% url 'profiles:profile' %}" class="neon-green-btn">
            <i class="fas fa-arrow-left"></i>
            Go back to profile
        </a>
    </div>
</div>
{% endblock %}

profiles/templates/profiles/delete_address.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<h1>Welcome to My Website!</h1>
<p>This is the home page content.</p>
{% endblock %}

profiles/templates/profiles/delete_profile.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<h1>Delete Profile</h1>
<p>Are you sure you want to delete your profile?</p>
<form action="{% url 'profiles:delete_profile' %}" method="post">
  {% csrf_token %}
  <input type="submit" value="Delete">
  <a href="{% url 'profiles:profile' %}"><button type="button">Cancel</button></a>
</form>
{% endblock %}

profiles/templates/profiles/edit_address.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<h1>Welcome to My Website!</h1>
<p>This is the home page content.</p>
{% endblock %}

profiles/templates/profiles/edit_profile.html
{% extends 'base.html' %}

{% block content %}
<div class="container" style="max-width: 800px; margin: 50px auto 20px; background-color: rgba(55, 55, 55, 0.8); border-radius: 10px; padding: 20px;">
    <h2 class="text-center text-white">Edit Profile</h2>
    <form method="post" class="row g-3" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="col-md-12 text-center mb-5">
            <div id="profile-picture-container" style="width: 200px; height: 200px; margin: auto;">
                {% if profile_form.instance.profile_picture %}
                    <img src="{{ profile_form.instance.profile_picture.url }}" alt="Profile Picture" class="img-fluid rounded-circle mb-3" style="width: 200px; height: 200px;">
                {% else %}
                    <img src="https://res.cloudinary.com/ds7qsnpge/image/upload/v1712528218/360_F_64676383_LdbmhiNM6Ypzb3FM4PPuFP9rHe7ri8Ju_yedqkn.jpg" alt="Default Profile Picture" class="img-fluid rounded-circle mb-3" style="width: 300px; height: 200px;">
                {% endif %}
            </div>
            <div>
                <button type="button" class="btn btn-success" id="edit-btn">
                    <i class="fas fa-pencil-alt"></i>
                    Edit</button>
                <button type="button" class="btn btn-danger" id="delete-btn">
                    <i class="fas fa-trash-alt"></i>
                    Delete</button>
            </div>
            <!-- Hidden file input field -->
            <input type="file" name="profile_picture" id="id_profile_picture" accept="image/*" class="d-none">
        </div>
        <div class="col-md-12" style="color: white;">
            <div class="row justify-content-center">
                <div class="col-md-6">
                    <h3>Profile Information</h3>
                    {{ profile_form.as_p }}
                </div>
                <div class="col-md-6">
                    <h3>Address Information</h3>
                    {{ address_form.as_p }}
                    <!-- Hidden input field for address information -->
                    <input type="hidden" name="address_info" value="{{ address_info }}">
                </div>
            </div>
        </div>
        <div class="col-md-12 text-center mt-5">
            <a href="{% url 'profiles:profile' %}" class="btn btn-secondary">
                <i class="fas fa-arrow-left"></i>
                Go back to profile
            </a>
            <button type="submit" class="btn btn-primary">Save Changes and Add Address</button>
            <a href="{% url 'profiles:delete_profile' %}" class="btn btn-danger">Delete Profile</a>
        </div>
    </form>
</div>

<style>
    /* CSS to hide the file input and its associated label */
    #id_profile_picture,
    #id_profile_picture + label {
        display: none;
    }

    /* Toastify message styling */
    .toast-container {
        position: fixed;
        top: 20px;
        right: 20px;
        z-index: 9999;
    }

    .toastify {
        background-color: #1c1c1c;
        color: #ffffff;
        padding: 10px 20px;
        border-radius: 5px;
        margin-bottom: 10px;
        box-shadow: 0 2px 5px rgba(0, 0, 0, 0.2);
    }

    .toastify-success {
        background-color: #c9fa04;
        color: #333;
    }

    .toastify-error {
        background-color: #ff6347;
        color: #ffffff;
    }
</style>

<script>
    document.getElementById('edit-btn').addEventListener('click', function() {
        // Trigger click event on file input
        document.getElementById('id_profile_picture').click();
    });

    document.getElementById('delete-btn').addEventListener('click', function() {
        if (confirm("Are you sure you want to delete the profile picture?")) {
            // Reset profile picture to default
            var profilePicture = document.querySelector('.img-fluid.rounded-circle.mb-3');
            profilePicture.src = "https://res.cloudinary.com/ds7qsnpge/image/upload/v1712528218/360_F_64676383_LdbmhiNM6Ypzb3FM4PPuFP9rHe7ri8Ju_yedqkn.jpg";
        }
    });

    // Add event listener to the form submission
    document.querySelector('form').addEventListener('submit', function(event) {
        // Prevent the default form submission behavior
        event.preventDefault();

        // Show toast notification
        Toastify({
            text: "Changes have been saved.",
            duration: 5000,
            close: false,
            backgroundColor: "linear-gradient(to right, #014e2a, #c9fa04)",
            gravity: "bottom",
            position: "center",
        }).showToast();

        // After displaying the message, submit the form
        this.submit();
    });
</script>
{% endblock %}

profiles/templates/profiles/profile.html
{% extends 'base.html' %}

{% block content %}
<div class="container" style="max-width: 400px; margin: 50px auto 0; background-color: rgba(55, 55, 55, 0.8); border-radius: 10px; padding: 20px;">
    <div class="row">
        <div class="col-md-12">
            <h2 class="text-center text-white">Welcome, {{ user.username }}</h2>
            <!-- Display user's name here -->
            <!-- Display user's profile image here -->
            <img src="https://res.cloudinary.com/ds7qsnpge/image/upload/v1712528218/360_F_64676383_LdbmhiNM6Ypzb3FM4PPuFP9rHe7ri8Ju_yedqkn.jpg" alt="User Image" class="img-fluid rounded-circle mb-3 mx-auto d-block">
            <hr>
            <h3 class="text-center text-white">Profile Options:</h3>
            <div class="vertical-links">
                <div><a href="{% url 'profiles:edit_profile' %}" class="btn btn-primary"><i class="bi bi-pencil" style="color: black;"></i> Edit Profile</a></div>
                <div><a href="{% url 'profiles:addresses' %}" class="btn btn-primary"><i class="bi bi-house" style="color: black;"></i> My Addresses</a></div>
                <div><a href="{% url 'profiles:edit_profile' %}" class="btn btn-primary"><i class="bi bi-plus" style="color: black;"></i> Add Address</a></div>
                <div><a href="{% url 'orders:user_order_list' %}" class="btn btn-primary"><i class="bi bi-bag" style="color: black;"></i> My Orders</a></div>
                <div><a href="{% url 'wishlist:view_wishlist' %}" class="btn btn-primary"><i class="bi bi-heart" style="color: black;"></i> My Wishlist</a></div>
            </div>
        </div>
    </div>
</div>

<style>
    .vertical-links {
        display: flex;
        flex-direction: column;
    }

    .vertical-links div {
        margin-bottom: 20px; /* Add some space between the links */
    }

    .vertical-links .btn {
        width: 100%; /* Make buttons fill the width of the container */
        text-align: left; /* Align button text to the left */
        display: flex; /* Use flexbox for icon and text alignment */
        align-items: center; /* Center items vertically */
        justify-content: center; /* Center items horizontally */
    }

    .vertical-links .btn i {
        margin-right: 10px; /* Add some space between the icon and text */
    }
</style>
{% endblock %}